@startuml
!include <C4/C4_Context>

title Диаграмма контекста системы управления отоплением и мониторинга

Person(User, "Пользователь", "Владелец или житель дома")
Person(Administrator, "Администратор", "Сотрудник компании")

System(WarmHouse, "Система Теплый дом", "Позволяет управлять устройствами, настройками отопления, предоставляет информацию о состоянии устройства")
System_Ext(Sensors, "Система отопления", "Система управления и датчики")

Rel(User, WarmHouse, "Устанавливает целевую температуру, управляет режимами, запрашивает данные о температуре")
Rel(Administrator, WarmHouse, "Управляет устройствами (добавляет, удаляет, изменяет конфигурацию)")

Rel(WarmHouse, Sensors, "Запрашивает данные о температуре, управляет устройством")
Rel(Sensors, WarmHouse, "Устройство производит регистрацию в системе")

@enduml