version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    container_name: smarthome-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "pg_isready --dbname=postgres --username=postgres && psql --username=postgres --list"
      start_period: 2s
      interval: 2s
      timeout: 3s
      retries: 5
    ports:
      - "5432"
    restart: unless-stopped
    networks:
      - smarthome-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD_ENCRYPTION=md5

  temperature-api:
    build:
        context: ./temperature-api
        dockerfile: Dockerfile
    hostname: temperature-api
    container_name: temperature-api
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge